### ISSUE TITLE
node download

### ISSUE THREAD

**Issue by cellurtech** [iPaulPro/CloutMask#2]
file that was down loaded to machine  for node  was moved and resuled in erorr need help if possible to whom this may concern THANK YOU !

**Comment by iPaulPro** [comment]
Hello, it's unclear what you are requesting, but this extension doesn't have anything to do with nodes.

Please provide more details.

**Comment by cellurtech** [comment]
Well basically the file that I downloaded for the node is not on my machine
like it has been  deleted  so it basically disappeared and I don't know if
it is from my machine but I have hundreds of photos that were duplicated on
there own for some reason  and I'm thinking that might have had something
to do with it I'm not sure  hope this helps thanks !

**Comment by iPaulPro** [comment]
I have no idea what you're talking about, as this project has nothing to do with nodes. I believe you may be filing this issue in the wrong place. This repository is not associated with BitClout core.

**Comment by cellurtech** [comment]
Oh ok my  bad thanks for help !!
